{
 "title": "AWS Network Firewall",
 "description": "Visualize AWS Network Firewall metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "firewallname",
    "label": "FirewallName",
    "query": "dimension_values($region, AWS/NetworkFirewall, Packets, FirewallName)"
   },
   {
    "name": "availabilityzone",
    "label": "AvailabilityZone",
    "query": "dimension_values($region, AWS/NetworkFirewall, Packets, AvailabilityZone)"
   },
   {
    "name": "engine",
    "label": "Engine",
    "query": "dimension_values($region, AWS/NetworkFirewall, Packets, Engine)"
   }
  ]
 },
 "panels": [
  {
   "title": "PassedPackets/DroppedPackets ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "AvailabilityZone": "$availabilityzone", "Engine": "$engine", "FirewallName": "$firewallname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "PassedPackets",
     "namespace": "AWS/NetworkFirewall",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "AvailabilityZone": "$availabilityzone", "Engine": "$engine", "FirewallName": "$firewallname" },
     "metricName": "DroppedPackets",
     "namespace": "AWS/NetworkFirewall",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReceivedPacketsCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "AvailabilityZone": "$availabilityzone", "Engine": "$engine", "FirewallName": "$firewallname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReceivedPacketCount",
     "namespace": "AWS/NetworkFirewall",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Packets/BytesOut",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "AvailabilityZone": "$availabilityzone", "Engine": "$engine", "FirewallName": "$firewallname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Packets",
     "namespace": "AWS/NetworkFirewall",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "TransitGateway": "$transitgateway" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesOut",
     "namespace": "AWS/TransitGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/network-firewall/latest/developerguide/monitoring-cloudwatch.html\">AWS CloudWatch Network Firewall documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/14955\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}