{
 "title": "AWS WAF",
 "description": "Visualize AWS WAF metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "Region",
    "label": "WAF Region",
    "query": "dimension_values($region,AWS/WAFV2,AllowedRequests,Region)"
   },
   {
    "name": "WebACL",
    "label": "WebACL",
    "query": "dimension_values($region,AWS/WAFV2,AllowedRequests,WebACL)"
   },
   {
    "name": "Rule",
    "label": "Rule",
    "query": "dimension_values($region,AWS/WAFV2,AllowedRequests,Rule)"
   },
   {
    "name": "RuleGroup",
    "label": "RuleGroup",
    "query": "dimension_values($region,AWS/WAFV2,AllowedRequests,RuleGroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "AllowedRequests/BlockedRequests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "AllowedRequests",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    },
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CountedRequests/PassedRequests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    },
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "PassedRequests",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CaptchaRequests/RequestsWithValidCaptchaToken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "CaptchaRequests",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    },
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "RequestsWithValidCaptchaToken",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CaptchasAttempted/CaptchasSolved",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "CaptchasAttempted",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    },
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "CaptchasSolved",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ChallengeRequests/RequestsWithValidChallengeToken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "ChallengeRequests",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    },
    {
     "alias": "{{ metric }} {{ Region }} {{ WebACL }} {{ Rule }}",
     "dimensions": { "Region": "$Region", "Rule": "$Rule", "WebACL": "$WebACL" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Region')} ${PROP('Dim.WebACL')} ${PROP('Dim.Rule')}",
     "metricName": "RequestsWithValidChallengeToken",
     "namespace": "AWS/WAFV2",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/waf/latest/developerguide/waf-metrics.html\">AWS CloudWatch WAF documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/20009\">Installed from Grafana.com dashboards</a>\n"
   }
  }
 ]
}