{
 "title": "AWS Route 53",
 "description": "Visualize AWS Route 53 metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "healthcheckid",
    "label": "HealthCheckId",
    "query": "dimension_values($region,AWS/Route53,HealthCheckStatus, HealthCheckId)"
   }
  ]
 },
 "panels": [
  {
   "title": "HealthCheckPercentageHealthy/ChildHealthCheckHealthyCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HealthCheckPercentageHealthy",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ChildHealthCheckHealthyCount",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ConnectionTime/TimeToFirstByte",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConnectionTime",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TimeToFirstByte",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HealthCheckStatus",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HealthCheckStatus",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "SSLHandshakeTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "HealthCheckId": "$healthcheckid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SSLHandshakeTime",
     "namespace": "AWS/Route53",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/monitoring-cloudwatch.html\">AWS CloudWatch Route 53 documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/11154\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}