{
 "title": "AWS Prometheus",
 "description": "Visualize AWS Prometheus metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1m,5m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "workspace",
    "label": "Workspace",
    "query": "dimension_values($region,AWS/Usage, ResourceCount, ResourceId)"
   },
   {
    "name": "rulegroup",
    "label": "RuleGroup",
    "query": "dimension_values($region,AWS/Prometheus, RuleEvaluations, RuleGroup, {\"Workspace\": \"${workspace:raw}\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "IngestionRate/ActiveSeries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "IngestionRate_Average",
     "application": { "filter": "" },
     "dimensions": {
      "Class": "None",
      "Resource": "IngestionRate",
      "ResourceId": "$workspace",
      "Service": "Prometheus",
      "Type": "Resource"
     },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "IngestionRate",
     "metricName": "ResourceCount",
     "namespace": "AWS/Usage",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "ActiveSeries_Average",
     "application": { "filter": "" },
     "dimensions": {
      "Class": "None",
      "Resource": "ActiveSeries",
      "ResourceId": "$workspace",
      "Service": "Prometheus",
      "Type": "Resource"
     },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "ActiveSeries",
     "metricName": "ResourceCount",
     "namespace": "AWS/Usage",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ActiveAlerts/SizeOfAlerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "ActiveAlerts_Average",
     "application": { "filter": "" },
     "dimensions": {
      "Class": "None",
      "Resource": "ActiveAlerts",
      "ResourceId": "$workspace",
      "Service": "Prometheus",
      "Type": "Resource"
     },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "ActiveAlerts",
     "metricName": "ResourceCount",
     "namespace": "AWS/Usage",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "SizeOfAlerts_Average",
     "application": { "filter": "" },
     "dimensions": {
      "Class": "None",
      "Resource": "SizeOfAlerts",
      "ResourceId": "$workspace",
      "Service": "Prometheus",
      "Type": "Resource"
     },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "SizeOfAlerts",
     "metricName": "ResourceCount",
     "namespace": "AWS/Usage",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "AlertManagerAlertsReceived/AlertManagerNotificationsFailed/AlertManagerNotificationsThrottled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "Workspace": "$workspace" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AlertManagerAlertsReceived",
     "namespace": "AWS/Prometheus",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "Workspace": "$workspace" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AlertManagerNotificationsFailed",
     "namespace": "AWS/Prometheus",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "Workspace": "$workspace" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AlertManagerNotificationsThrottled",
     "namespace": "AWS/Prometheus",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DiscardedSamples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{Reason}}",
     "application": { "filter": "" },
     "dimensions": { "Reason": "*", "Workspace": "$workspace" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiscardedSamples",
     "namespace": "AWS/Prometheus",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RuleEvaluations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{RuleGroup}}",
     "application": { "filter": "" },
     "dimensions": { "RuleGroup": "$rulegroup", "Workspace": "$workspace" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Dim.RuleGroup')}",
     "metricName": "RuleEvaluations",
     "namespace": "AWS/Prometheus",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RuleEvaluationFailures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{RuleGroup}}",
     "application": { "filter": "" },
     "dimensions": { "RuleGroup": "$rulegroup", "Workspace": "$workspace" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Dim.RuleGroup')}",
     "metricName": "RuleEvaluationFailures",
     "namespace": "AWS/Prometheus",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RuleGroupIterationsMissed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{RuleGroup}}",
     "application": { "filter": "" },
     "dimensions": { "RuleGroup": "$rulegroup", "Workspace": "$workspace" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Dim.RuleGroup')}",
     "metricName": "RuleGroupIterationsMissed",
     "namespace": "AWS/Prometheus",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-CW-usage-metrics.html\">AWS CloudWatch Prometheus documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/16899\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}