name: Duplicates

on:
  workflow_dispatch:

jobs:
  test:
    name: Find duplicates
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Find duplicates
        run: python .github/workflows/find-duplicates.py
